### ISSUE TITLE
feature request: list of all memory pointers/offsets

### ISSUE THREAD

**Issue by OtterSou** [RoboLP/EDGE#1]
a few of wiki pages list the relevant memory pointers/offsets, but I think it's useful to have a page that lists all memory pointers/offsets that you're aware of.

**Comment by robin-mu** [comment]
Good idea! If you want to have my CheatEngine file you can message me on Discord (robin.mu). Apart from that, I will create a wiki page in the next days

**Comment by robin-mu** [comment]
[Done!](https://github.com/robin-mu/EDGE/wiki/Memory-Pointers)
